Configuraiton.UserInterface/Models/ErrorViewModel.cs
namespace Configuration.UserInterface.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Configuraiton.UserInterface/Controllers/ConfigurationEntityController.cs
using AutoMapper;
using Configuration.Business.Abstract;
using Configuration.Data.Entities;
using Configuration.UserInterface.VMs;
using Microsoft.AspNetCore.Mvc;

namespace Configuration.UserInterface.Controllers
{
    public class ConfigurationEntityController : Controller
    {
        private IConfigurationService _configurationService;
        private IMapper _mapper;

        public ConfigurationEntityController(IConfigurationService configurationService, IMapper mapper)
        {
            _configurationService = configurationService;
            _mapper = mapper;
        }

        public IActionResult Index(string searchTerm = null)
        {
            var configurationList = string.IsNullOrEmpty(searchTerm)
                ? _configurationService.TGetAll().ToList()
                : _configurationService.TSearch(searchTerm).ToList();

            ViewData["searchTerm"] = searchTerm;
            return View(configurationList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateConfigurationEntityVM model)
        {
            _configurationService.TAddAsync(new ConfigurationEntity()
            {
                ApplicationName = model.ApplicationName,
                IsActive = model.IsActive,
                Name = model.Name,
                Type = model.Type,
                Value = model.Value
            });
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var configuration = _configurationService.TGetById(id);
            var model = new UpdateConfigurationEntityVM()
            {
                Id = configuration.Id,
                ApplicationName = configuration.ApplicationName,
                IsActive = configuration.IsActive,
                Name = configuration.Name,
                Type = configuration.Type,
                Value = configuration.Value
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(UpdateConfigurationEntityVM model)
        {
            var configurationEntity = _mapper.Map<ConfigurationEntity>(model);
            _configurationService.TUpdateAsync(configurationEntity);
            return RedirectToAction("Index");
        }

        [HttpGet("{id}")]
        public IActionResult GetById(int id)
        {
            var configurationEntity = _configurationService.TGetById(id);
            return Ok(configurationEntity);
        }

    }
}

Configuraiton.UserInterface/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Configuraiton.UserInterface.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

Configuraiton.UserInterface/Views/ConfigurationEntity/Create.cshtml
@model CreateConfigurationEntityVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create Configuration Entity</h1>
<div>
    <form method="post">
        <div class="form-group">
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="ApplicationName"></label>
            <input type="text" asp-for="ApplicationName" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Type"></label>
            <input type="text" asp-for="Type" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Value"></label>
            <input type="text" asp-for="Value" class="form-control" />
        </div>
        <div class="form-group form-check">
            <input type="checkbox" asp-for="IsActive" class="form-check-input" />
            <label asp-for="IsActive" class="form-check-label"></label>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

Configuraiton.UserInterface/Views/ConfigurationEntity/Edit.cshtml
@model UpdateConfigurationEntityVM

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Configuration Entity</h1>
<div>
    <form asp-action="Edit" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="ApplicationName"></label>
            <input type="text" asp-for="ApplicationName" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Type"></label>
            <input type="text" asp-for="Type" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Value"></label>
            <input type="text" asp-for="Value" class="form-control" />
        </div>
        <div class="form-group form-check">
            <input type="checkbox" asp-for="IsActive" class="form-check-input" />
            <label asp-for="IsActive" class="form-check-label"></label>
        </div>
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>
</div>

Configuraiton.UserInterface/Views/ConfigurationEntity/Index.cshtml
@model List<ConfigurationEntity>

@{
    ViewData["Title"] = "Index";
}

<script src="~/microsoft/signalr/dist/browser/signalr.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@* SignalR Scripts *@

<script type="text/javascript">

    $(document).ready(() => {

        var connection = new signalR.HubConnectionBuilder().withUrl("/signalrhub").build();
        $("#connstatus").text(connection.state);
        connection.start().then(() => {
            $("#connstatus").text(connection.state);
            setInterval(() => {
                connection.invoke("SendConfigurationList");
            }, 1000);
        }).catch((err) => { console.error(err) });

        connection.on("ReceiveConfigurationList", (configurationList) => {
            console.log(configurationList);
            let tablehtml = `<table class="table">
                                            <thead>
                                                <tr>
                                                    <th>
                                                        #
                                                    </th>
                                                    <th>
                                                        Name
                                                    </th>
                                                    <th>
                                                        ApplicationName
                                                    </th>
                                                    <th>
                                                        Type
                                                    </th>
                                                    <th>
                                                        Value
                                                    </th>
                                                    <th>
                                                        IsActive
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>`;
            $.each(configurationList, (index, item) => {
                tablehtml += `<tr>
                                                <td>
                                                    ${item.id}
                                                </td>
                                                <td>
                                                    ${item.name}
                                                </td>
                                                <td>
                                                    ${item.applicationName}
                                                </td>
                                                <td>
                                                    ${item.type}
                                                </td>
                                                <td>
                                                    ${item.value}
                                                </td>
                                                <td>
                                                    ${item.isActive}
                                                </td>
                                                <td>
                                                        <a href="/ConfigurationEntity/Edit/${item.id}">Edit</a>
                                                </td>
                                            </tr>`;
            });
            tablehtml += `</tbody></table>`;
            $("#configurationList").html(tablehtml);
        });
    });

</script>

<div>
    <h1>Configuration Entities</h1>
    <form method="get" asp-action="Index">
        <div class="form-group">
            <input type="text" name="searchTerm" class="form-control" placeholder="Search..." value="@ViewData["searchTerm"]" />
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </form>
    <div id="configurationList"></div>
    <br /> <br />
    <a asp-action="Create">Create New</a>
</div>

Configuraiton.UserInterface/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Configuraiton.UserInterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Configuration.UserInterface</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Configuration.UserInterface.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ConfigurationEntity" asp-action="Index">Configuration.UserInterface</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ConfigurationEntity" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Configuration.UserInterface - <a asp-area="" asp-controller="ConfigurationEntity" asp-action="Index">Configuration List</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>